[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0033A0"         # CUNY Blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"  # soft off-white
textColor = "#1F2937"            # dark slate
